---
- hosts: planet,micro
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - apigee-opdk-setup-default-settings
  tags:
  - cache
  - os-pre-req
  - apigee-pre-req

- hosts: micro
  become: yes
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - apigee-opdk-setup-os-minimum
  - apigee-opdk-setup-os-common

  tasks:
  - name: Install needed Python used for downloading files with https
    pip:
      name: '{{ item }}'
      state: present
    with_items:
    - urllib3
    - pyopenssl
    - ndg-httpsclient
    - pyasn1
    tags:
    - os-pre-req

  - name: Download Node 6.x package manager configuration script
    get_url:
      url: https://rpm.nodesource.com/setup_6.x
      dest: /tmp/setup_node.sh
      mode: 0700
    tags:
    - os-pre-req


  - name: Setup Node 6.x package manager
    shell: "/tmp/setup_node.sh"
    tags:
    - os-pre-req

  - name:  Install Yum packages
    yum:
      name: '{{ item }}'
      state: present
    with_items:
    - nodejs
    - gcc-c++
    - make
    tags:
    - os-pre-req

  - name: Install edgemicro
    npm:
      name: '{{ item.name }}'
      version: '{{ item.version }}'
      path: '~'
      global: true
      state: present
    with_items:
    - { name: edgemicro, version: '2.1.1' }
    tags:
    - os-pre-req

- hosts: micro
  become: true
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - apigee-opdk-setup-default-settings
  tasks:

  - name: Init edgemicro
    shell: 'edgemicro init'
    args:
      chdir: '~'
    tags:
    - apigee-pre-req

  - name: Get router public IP address
    set_fact:
      router_ip: "{{ hostvars[groups['rmp'][0]]['public_address'] }}"
    tags:
    - apigee-component

  - name: Configure edgemicro
    become: true
    delegate_to: '{{ inventory_hostname }}'
    shell: edgemicro private configure -m http://{{ local_mgmt_ip }}:8080 -r http://{{ router_ip }}:9001 -o {{ org_name }} -e {{ env_name }} -u {{ opdk_user_email }} -p {{ opdk_user_pass }} -v default
    args:
      chdir: '~'
    tags:
    - apigee-component
