---
- hosts: micro
  become: yes
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - apigee-opdk-setup-os-minimum
  - apigee-opdk-setup-os-common


  tasks:
  - name: Install needed Python used for downloading files with https
    pip:
      name: '{{ item }}'
      state: present
    with_items:
    - urllib3
    - pyopenssl
    - ndg-httpsclient
    - pyasn1
    tags:
    - os-pre-req

  - name: Download Node 6.x package manager configuration script
    get_url:
      url: https://rpm.nodesource.com/setup_6.x
      dest: /tmp/setup_node.sh
      mode: 0700
    tags:
    - os-pre-req


  - name: Setup Node 6.x package manager
    shell: "/tmp/setup_node.sh"
    tags:
    - os-pre-req

  - name:  Install Yum packages
    yum:
      name: '{{ item }}'
      state: present
    with_items:
    - nodejs
    - gcc-c++
    - make
    tags:
    - os-pre-req

  - name: Install edgemicro
    npm:
      name: '{{ item.name }}'
      version: '{{ item.version }}'
      path: '~'
      global: true
      state: present
    with_items:
    - { name: edgemicro, version: '2.1.1' }
    tags:
    - os-pre-req
